# Generated by Django 4.0.5 on 2022-06-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='podcasts',
            new_name='podcast',
        ),
    ]
