# Generated by Django 4.0.5 on 2022-06-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_rename_podcasts_podcast'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='podcast',
            new_name='Item',
        ),
    ]
