# Generated by Django 4.0.5 on 2022-06-14 20:03

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_rename_podcast_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='SOME STRING'),
        ),
    ]
