# Generated by Django 4.0.5 on 2022-06-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_item_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
    ]
