# Generated by Django 4.0.5 on 2022-09-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_usuario_email_remove_usuario_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='consulta',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
