# Generated by Django 4.0.5 on 2022-09-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_usuario_consulta_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='consulta',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mail',
            field=models.EmailField(max_length=20),
        ),
    ]
